name: agriapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core_platform_interface: 4.4.1
  firebase_auth_platform_interface: 6.2.5
  firebase_auth: 3.3.17
  firebase_core: 1.18.0
  cloud_firestore: ^3.1.14
  flutter_local_notifications: ^9.2.0
  firebase_messaging: ^11.2.6
  rflutter_alert: ^2.0.4
  modal_progress_hud_nsn: ^0.2.1
  http: ^0.13.4
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^10.1.0
  buttons_tabbar: ^1.3.6
  line_icons: ^2.0.1
  fl_chart: ^0.55.0
  intl: ^0.17.0
  data_table_2: ^2.3.5
  image_picker: ^0.8.5+3
  cloud_functions: ^3.3.0
  firebase_storage: ^10.2.17
  path_provider: ^2.0.11
  provider: ^6.0.3
  fluttertoast: ^8.0.9
  lottie: ^1.3.0
  shared_preferences: ^2.0.15
  get: ^4.6.5
  google_nav_bar: ^5.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/animations/
